# Generated by Django 6.0.7 on 2026-08-28 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_code', models.CharField(default='EPAYTEST', editable=False, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting sandbox payment'), ('PAID', 'Sandbox payment verified'), ('EXPIRED', 'Expired or cancelled'), ('REVIEW', 'Payment received - manual review/refund required')], default='PENDING', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='appointments.appointment')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_payment_amount')],
            },
        ),
    ]
