# Generated by Django 6.0.7 on 2026-09-01 04:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service_type', models.CharField(choices=[('EMERGENCY', 'Emergency SOS'), ('TRANSFER', 'Hospital transfer'), ('SCHEDULED', 'Scheduled transport')], max_length=20)),
                ('patient_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('CONTACTED', 'Caller contacted'), ('DISPATCHED', 'Dispatched'), ('CLOSED', 'Closed')], default='RECEIVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
