# Generated by Django 6.0.7 on 2026-09-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctoravailability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['weekday', 'start_time']},
        ),
        migrations.RemoveConstraint(
            model_name='doctoravailability',
            name='one_schedule_per_doctor_day',
        ),
        migrations.AddConstraint(
            model_name='doctoravailability',
            constraint=models.UniqueConstraint(fields=('doctor', 'weekday', 'start_time', 'end_time'), name='unique_doctor_schedule_window'),
        ),
    ]
